<?php
// $Id$

/**
 * @file
 */

/**
 * Implementation of hook_menu().
 */
function ascribda_menu($may_cache) {
  $items = array();

  if ($may_cache) {
    $items[] = array(
      'path' => 'admin/settings/ascribda',
      'title' => t('Auto Scribdizing Attachments configuration'),
      'description' => t('You can set how attachment files will be converted to scribd documents'),
      'callback' => 'drupal_get_form',
      'callback arguments' => 'ascribda_settings_form',
    );
  }
  
  return $items;
}

/**
 * @file
 * Callback funtion.
 *
 * 
 */
function ascribda_settings_form() {
  $form = array();

  return system_settings_form($form);
}

/**
 * Implementation of hook_nodeapi().
 */
function ascribda_nodeapi(&$node, $op) {
  global $user; if ($user->uid != 1) return;
  if (($op == 'insert' || $op == 'update') && $node->type != 'ipaper') {
    // Check if there is files.
    if (!empty($node->files)) {
      require_once(drupal_get_path('module', 'ascribda') .'/scribd/scribd.php');

      foreach ($node->files as $file) {
        $file = (object) $file;
        if ($file->filemime != 'application/pdf' && !mb_ereg_match(".*\.pdf$", $file->filename)) {
	  continue;
        }

        // Find if it's uploaded alreay.
	$sql = "SELECT doc_id FROM {ascribda_docinfo}
	        WHERE fid = %d AND nid = %d AND vid =%d";
        $is_uploaded = db_result(db_query($sql, $file->fid, $node->nid, $node->vid));

	if (!$is_uploaded) {
	  $scribd_api_key = unserialize(variable_get('scribd_api_key', 0));
	  $scribd_secret = unserialize(variable_get('scribd_secret_key', 0));

	  // Initialize scribd object.
	  $scribd = new Scribd($scribd_api_key, $scribd_secret);

	  $pdffile = getcwd() .'/'. $file->filepath;
	  $doc_type = 'pdf';
	  $access = 'public';
	  $rev_id = null;

          // Begin upload.
	  $data = $scribd->upload($pdffile, $doc_type, $access, $rev_id);

	  if ($data) {
	    // If success, save to db.
	    $sql = "INSERT INTO {ascribda_docinfo}
	            VALUES (%d, %d, %d, %d, '%s')";
	    $result = db_query($sql, $node->nid, $node->vid, $file->fid, $data['doc_id'], $data['access_key']);
	    if ($result) {
	      drupal_set_message("Upload to scribd successful.");
	    }
	  }
	  else {
	    drupal_set_message("Cannot upload attachment file: $file->filename now. Please try again later.", 'warning');
	  }
	}
      }
    }
  }
}

